import 'dart:ffi';
import 'dart:io';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

/// Service to communicate with the Rust core engine via flutter_rust_bridge
class BridgeService {
  static BridgeService? _instance;
  late final RustLibApi _api;

  BridgeService._() {
    _api = RustLibApi();
  }

  static BridgeService get instance {
    _instance ??= BridgeService._();
    return _instance!;
  }

  RustLibApi get api => _api;

  /// Initialize the Rust core engine
  Future<void> init() async {
    await _api.init();
  }

  /// Health check
  Future<String> healthCheck() async {
    return await _api.healthCheck();
  }
}

/// Stub API class — generated by flutter_rust_bridge_codegen
/// This will be replaced by the generated code after running the codegen
class RustLibApi {
  Future<void> init() async {}
  Future<String> healthCheck() async => 'OK';
  Future<String> sendChat(Map<String, dynamic> request) async => '';
  Future<Map<String, dynamic>> validateKey(String provider, String apiKey, String? baseUrl) async => {};
  Future<List<dynamic>> fetchModels(String provider, String apiKey, String? baseUrl) async => [];
  Future<Map<String, dynamic>> analyzeSentiment(String text) async => {};
  Future<Map<String, dynamic>> detectLanguage(String text) async => {};
  Future<void> saveMemory(String id, String key, String value, String category) async {}
  Future<List<dynamic>> getMemories() async => [];
  Future<void> deleteMemory(String id) async {}
  Future<void> saveKnowledge(String id, String title, String content, String? source, String? tags) async {}
  Future<List<dynamic>> getKnowledgeDocuments() async => [];
  Future<void> deleteKnowledge(String id) async {}
  Future<List<dynamic>> searchKnowledge(String query, int limit) async => [];
  Future<void> recordUsage(String provider, String model, int promptTokens, int completionTokens, double cost, int latencyMs) async {}
  Future<List<dynamic>> getUsageStats(int limit) async => [];
}
